export enum Key {
    BACKSPACE = 'BACKSPACE',
    TAB = 'TAB',
    ENTER = 'ENTER',
    RETURN = 'RETURN',
    SHIFT = 'SHIFT',
    LSHIFT = 'LSHIFT',
    RSHIFT = 'RSHIFT',
    CTRL = 'CTRL',
    LCTRL = 'LCTRL',
    RCTRL = 'RCTRL',
    ALT = 'ALT',
    LALT = 'LALT',
    RALT = 'RALT',
    PAUSE_BREAK = 'PAUSE_BREAK',
    CAPS = 'CAPS',
    ESC = 'ESC',
    SPACE = 'SPACE',
    PAGE_UP = 'PAGE_UP',
    PAGE_DOWN = 'PAGE_DOWN',
    END = 'END',
    HOME = 'HOME',
    LEFT = 'LEFT',
    UP = 'UP',
    RIGHT = 'RIGHT',
    DOWN = 'DOWN',
    INSERT = 'INSERT',
    DELETE = 'DELETE',
    DASH = 'DASH',
    HYPHEN = 'HYPHEN',
    MINUS = 'MINUS',
    UNDERSCORE = 'UNDERSCORE',
    EQUALS = 'EQUALS',
    PLUS = 'PLUS',
    TICK = 'TICK',
    TILDA = 'TILDA',
    ZERO = 'ZERO',
    CLOSE_PAREN = 'CLOSE_PAREN',
    ONE = 'ONE',
    BANG = 'BANG',
    EXCLAMATION_POINT = 'EXCLAMATION_POINT',
    TWO = 'TWO',
    AT = 'AT',
    THREE = 'THREE',
    HASH = 'HASH',
    POUND = 'POUND',
    FOUR = 'FOUR',
    DOLLAR = 'DOLLAR',
    FIVE = 'FIVE',
    PERCENT = 'PERCENT',
    SIX = 'SIX',
    CARET = 'CARET',
    UP_CARET = 'UP_CARET',
    SEVEN = 'SEVEN',
    AMPERSAND = 'AMPERSAND',
    EIGHT = 'EIGHT',
    ASTERISK = 'ASTERISK',
    NINE = 'NINE',
    OPEN_PAREN = 'OPEN_PAREN',
    F1 = 'F1',
    F2 = 'F2',
    F3 = 'F3',
    F4 = 'F4',
    F5 = 'F5',
    F6 = 'F6',
    F7 = 'F7',
    F8 = 'F8',
    F9 = 'F9',
    F10 = 'F10',
    F11 = 'F11',
    F12 = 'F12',
    CONTEXT_MENU = 'CONTEXT_MENU',
    SELECT = 'SELECT',
    NUM_LOCK = 'NUM_LOCK',
    SCROLL_LOCK = 'SCROLL_LOCK',
    NUMPAD_ZERO = 'NUMPAD_ZERO',
    NUMPAD_ONE = 'NUMPAD_ONE',
    NUMPAD_TWO = 'NUMPAD_TWO',
    NUMPAD_THREE = 'NUMPAD_THREE',
    NUMPAD_FOUR = 'NUMPAD_FOUR',
    NUMPAD_FIVE = 'NUMPAD_FIVE',
    NUMPAD_SIX = 'NUMPAD_SIX',
    NUMPAD_SEVEN = 'NUMPAD_SEVEN',
    NUMPAD_EIGHT = 'NUMPAD_EIGHT',
    NUMPAD_NINE = 'NUMPAD_NINE',
    NUMPAD_DIVIDE = 'NUMPAD_DIVIDE',
    NUMPAD_MULTIPLY = 'NUMPAD_MULTIPLY',
    NUMPAD_SUBTRACT = 'NUMPAD_SUBTRACT',
    NUMPAD_ADD = 'NUMPAD_ADD',
    NUMPAD_ENTER = 'NUMPAD_ENTER',
    NUMPAD_DECIMAL = 'NUMPAD_DECIMAL',
    A = 'A',
    B = 'B',
    C = 'C',
    D = 'D',
    E = 'E',
    F = 'F',
    G = 'G',
    H = 'H',
    I = 'I',
    J = 'J',
    K = 'K',
    L = 'L',
    M = 'M',
    N = 'N',
    O = 'O',
    P = 'P',
    Q = 'Q',
    R = 'R',
    S = 'S',
    T = 'T',
    U = 'U',
    V = 'V',
    W = 'W',
    X = 'X',
    Y = 'Y',
    Z = 'Z',
    COMMA = 'COMMA',
    LEFT_CARET = 'LEFT_CARET',
    SEMI_COLON = 'SEMI_COLON',
    COLON = 'COLON',
    PERIOD = 'PERIOD',
    RIGHT_CARET = 'RIGHT_CARET',
    FORWARD_SLASH = 'FORWARD_SLASH',
    QUESTION_MARK = 'QUESTION_MARK',
    OPEN_SQUARE_BRACKET = 'OPEN_SQUARE_BRACKET',
    CLOSE_SQUARE_BRACKET = 'CLOSE_SQUARE_BRACKET',
    OPEN_CURLY_BRACKET = 'OPEN_CURLY_BRACKET',
    CLOSE_CURLY_BRACKET = 'CLOSE_CURLY_BRACKET',
    BACK_SLASH = 'BACK_SLASH',
    DOUBLE_QUOTE = 'DOUBLE_QUOTE',
    SINGLE_QUOTE = 'SINGLE_QUOTE',
    APOSTROPHE = 'APOSTROPHE',
    LEFT_WINDOWS = 'LEFT_WINDOWS',
    RIGHT_WINDOWS = 'RIGHT_WINDOWS',
    BAR = 'BAR',
    PIPE = 'PIPE'
};

export const KeysByKeyCode: { [keyCode: number]: Key[] } = {
    8: [Key.BACKSPACE],
    9: [Key.TAB],
    16: [Key.SHIFT],
    17: [Key.CTRL],
    18: [Key.ALT],
    19: [Key.PAUSE_BREAK],
    20: [Key.CAPS],
    27: [Key.ESC],
    32: [Key.SPACE],
    33: [Key.PAGE_UP],
    34: [Key.PAGE_DOWN],
    35: [Key.END],
    36: [Key.HOME],
    37: [Key.LEFT],
    38: [Key.UP],
    39: [Key.RIGHT],
    40: [Key.DOWN],
    45: [Key.INSERT],
    48: [Key.ZERO, Key.CLOSE_PAREN],
    49: [Key.ONE, Key.BANG, Key.EXCLAMATION_POINT],
    50: [Key.TWO, Key.AT],
    51: [Key.THREE, Key.HASH, Key.POUND],
    52: [Key.FOUR, Key.DOLLAR],
    53: [Key.FIVE, Key.PERCENT],
    54: [Key.SIX, Key.CARET, Key.UP_CARET],
    55: [Key.SEVEN, Key.AMPERSAND],
    56: [Key.EIGHT, Key.ASTERISK],
    57: [Key.NINE, Key.OPEN_PAREN],
    65: [Key.A],
    66: [Key.B],
    67: [Key.C],
    68: [Key.D],
    69: [Key.E],
    70: [Key.F],
    71: [Key.G],
    72: [Key.H],
    73: [Key.I],
    74: [Key.J],
    75: [Key.K],
    76: [Key.L],
    77: [Key.M],
    78: [Key.N],
    79: [Key.O],
    80: [Key.P],
    81: [Key.Q],
    82: [Key.R],
    83: [Key.S],
    84: [Key.T],
    85: [Key.U],
    86: [Key.V],
    87: [Key.W],
    88: [Key.X],
    89: [Key.Y],
    90: [Key.Z],
    91: [Key.LEFT_WINDOWS],
    92: [Key.RIGHT_WINDOWS],
    93: [Key.CONTEXT_MENU, Key.SELECT],
    96: [Key.NUMPAD_ZERO],
    97: [Key.NUMPAD_ONE],
    98: [Key.NUMPAD_TWO],
    99: [Key.NUMPAD_THREE],
    100: [Key.NUMPAD_FOUR],
    101: [Key.NUMPAD_FIVE],
    102: [Key.NUMPAD_SIX],
    103: [Key.NUMPAD_SEVEN],
    104: [Key.NUMPAD_EIGHT],
    105: [Key.NUMPAD_NINE],
    106: [Key.NUMPAD_MULTIPLY],
    107: [Key.NUMPAD_ADD],
    109: [Key.NUMPAD_SUBTRACT],
    110: [Key.NUMPAD_DECIMAL],
    111: [Key.NUMPAD_DIVIDE],
    112: [Key.F1],
    113: [Key.F2],
    114: [Key.F3],
    115: [Key.F4],
    116: [Key.F5],
    117: [Key.F6],
    118: [Key.F7],
    119: [Key.F8],
    120: [Key.F9],
    121: [Key.F10],
    122: [Key.F11],
    123: [Key.F12],
    144: [Key.NUM_LOCK],
    145: [Key.SCROLL_LOCK],
    186: [Key.SEMI_COLON, Key.COLON],
    187: [Key.EQUALS, Key.PLUS],
    188: [Key.COMMA, Key.LEFT_CARET],
    189: [Key.DASH, Key.HYPHEN, Key.MINUS, Key.UNDERSCORE],
    190: [Key.PERIOD, Key.RIGHT_CARET],
    191: [Key.FORWARD_SLASH, Key.QUESTION_MARK],
    192: [Key.TICK, Key.TILDA],
    219: [Key.OPEN_SQUARE_BRACKET, Key.OPEN_CURLY_BRACKET],
    220: [Key.BACK_SLASH, Key.BAR, Key.PIPE],
    221: [Key.CLOSE_SQUARE_BRACKET, Key.CLOSE_CURLY_BRACKET],
    222: [Key.DOUBLE_QUOTE, Key.SINGLE_QUOTE, Key.APOSTROPHE]
};

export const CharactersByKeyCode: { [key: number]: { lower: string, upper: string } } = {
    [9]: { lower: '\t', upper: '\t' },
    [13]: { lower: '\n', upper: '\n' },
    [32]: { lower: ' ', upper: ' ' },
    [48]: { lower: '0', upper: ')' },
    [49]: { lower: '1', upper: '!' },
    [50]: { lower: '2', upper: '@' },
    [51]: { lower: '3', upper: '#' },
    [52]: { lower: '4', upper: '$' },
    [53]: { lower: '5', upper: '%' },
    [54]: { lower: '6', upper: '^' },
    [55]: { lower: '7', upper: '&' },
    [56]: { lower: '8', upper: '*' },
    [57]: { lower: '9', upper: '(' },
    [65]: { lower: 'a', upper: 'A' },
    [66]: { lower: 'b', upper: 'B' },
    [67]: { lower: 'c', upper: 'C' },
    [68]: { lower: 'd', upper: 'D' },
    [69]: { lower: 'e', upper: 'E' },
    [70]: { lower: 'f', upper: 'F' },
    [71]: { lower: 'g', upper: 'G' },
    [72]: { lower: 'h', upper: 'H' },
    [73]: { lower: 'i', upper: 'I' },
    [74]: { lower: 'j', upper: 'J' },
    [75]: { lower: 'k', upper: 'K' },
    [76]: { lower: 'l', upper: 'L' },
    [77]: { lower: 'm', upper: 'M' },
    [78]: { lower: 'n', upper: 'N' },
    [79]: { lower: 'o', upper: 'O' },
    [80]: { lower: 'p', upper: 'P' },
    [81]: { lower: 'q', upper: 'Q' },
    [82]: { lower: 'r', upper: 'R' },
    [83]: { lower: 's', upper: 'S' },
    [84]: { lower: 't', upper: 'T' },
    [85]: { lower: 'u', upper: 'U' },
    [86]: { lower: 'v', upper: 'V' },
    [87]: { lower: 'w', upper: 'W' },
    [88]: { lower: 'x', upper: 'X' },
    [89]: { lower: 'y', upper: 'Y' },
    [90]: { lower: 'z', upper: 'Z' },
    [96]: { lower: '0', upper: '0' },
    [97]: { lower: '1', upper: '1' },
    [98]: { lower: '2', upper: '2' },
    [99]: { lower: '3', upper: '3' },
    [100]: { lower: '4', upper: '4' },
    [101]: { lower: '5', upper: '5' },
    [102]: { lower: '6', upper: '6' },
    [103]: { lower: '7', upper: '7' },
    [104]: { lower: '8', upper: '8' },
    [105]: { lower: '9', upper: '9' },
    [106]: { lower: '*', upper: '*' },
    [107]: { lower: '+', upper: '+' },
    [109]: { lower: '-', upper: '-' },
    [110]: { lower: '.', upper: '.' },
    [111]: { lower: '/', upper: '/' },
    [186]: { lower: ';', upper: ':' },
    [187]: { lower: '=', upper: '+' },
    [188]: { lower: ',', upper: '<' },
    [189]: { lower: '-', upper: '_' },
    [190]: { lower: '.', upper: '>' },
    [191]: { lower: '/', upper: '?' },
    [192]: { lower: '`', upper: '~' },
    [219]: { lower: '[', upper: '{' },
    [220]: { lower: '\\', upper: '|' },
    [221]: { lower: ']', upper: '}' },
    [222]: { lower: '\'', upper: '"' },
}